import observale from './observable';
import unsubscribe from './unsubscribe';
import create from './creation-operators';
import operators from './operators';
import distinct from './distinct';
import flattening from './flattening-operators';
import countDown from './count-down';
import share from './share';
import subject from './subject';

console.clear();
// observale();
// create();
// unsubscribe();
// operators();
// distinct();
// flattening();
// countDown();
// share();
subject();
